### ISSUE TITLE
Use A Serverless Function

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [ElGarash/Jitsi-Meetings-Dashboard#5]
This is the happy path:
1. Receive a `POST` request in the function which includes the meeting data.
2. Clone the repo and check out a branch, which will be used for the generated website usually when Github pages are used it's `gh-pages`.
3.Insert the meeting data in the `sqlite.db` file.
4. Push to Github, this will require a token.
5. Send a `success` response.

This issue is only concerned with writing to the database, the reading will be handled in another one.

**Comment by AbdulrhmnGhanem** [comment]
Add `sqlite.db` to `.gitignore` in the `main` branch, and leave it in the `gh-pages` branch.

**Comment by AbdulrhmnGhanem** [comment]
For deployment, check https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=python.

**Comment by nooreldeensalah** [comment]
> This is the happy path:
> 
> 1. Receive a POST request in the function which includes the meeting data.
> 2. Clone the repo and check out a branch, which will be used for the generated website usually when Github pages are used it's gh-pages.
>    3.Insert the meeting data in the sqlite.db file.
> 3. Push to Github, this will require a token.
> 4. Send a success response.
> 
> This issue is only concerned with writing to the database, the reading will be handled in another one.

- Implemented an Azure Function written in Python #6.
- I used [PyGitHub](https://github.com/PyGithub/PyGithub) to access GitHub API to get `database.db` file in `gh-pages` branch, then update it with the POST request payload contents. #7 
- Implemented JWT tokens authentication and validation with a third-party service [Auth0](https://auth0.com/) in #8.
- Implemented a continuous deployment GitHub Action which deploys the branch `main` to the function app at Azure #9.
